version: '3'
services:
  master:
    build: .
    # container_name: fastapi-google-sheets-app
    # image: google-sheets-async
    restart: always
    ports:
      - 8000:8000
    volumes:
      #from the root python project locally to the container
      - .:/app

  test:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["pytest", "-v", "-s"]
    # command: ["pytest", "--cov=.", "--cov-report=term-missing"]