version: '3'
services:
  master:
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      #from the root python project locally to the container
      - .:/app

  test:
    build:
      context: .
    volumes:
      - .:/app
    working_dir: /app
    command: ["pytest", "-v", "-s"]